spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=BD24132;encrypt=true;trustServerCertificate=true
    username: BD24132
    password: BD24132
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true